version: '3'

services:
  postgres:
    build:
      context: .
      dockerfile: docker/Dockerfile.postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    build:
      context: .
      dockerfile: docker/Dockerfile.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: email@bk.ru
      PGADMIN_DEFAULT_PASSWORD: mypgadminpassword
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  fastapi:
    build:
      context: .
      dockerfile: docker/Dockerfile.fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app

volumes:
  postgres_data:
  pgadmin_data: