version: '3'

services:
  postgres:
    build:
      context: .
      dockerfile: docker/Dockerfile.postgres
    env_file:
      - app/.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    build:
      context: .
      dockerfile: docker/Dockerfile.pgadmin
    env_file:
      - app/.env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  fastapi:
    build:
      context: .
      dockerfile: docker/Dockerfile.fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app

  redis:
    build:
      context: .
      dockerfile: docker/Dockerfile.redis
    ports:
      - "6379:6379"

  bot:
    build:
      context: .
      dockerfile: docker/Dockerfile.bot
    env_file:
      - app/.env
    environment:
      BOT_TOKEN: ${API_BOT_TOKEN}
    ports:
      - "3000:3000"
    volumes:
      - ./app:/code/app

volumes:
  postgres_data:
  pgadmin_data: