# Используем официальный образ PostgreSQL
FROM postgres:latest

# Добавляем скрипт инициализации (если необходимо)
# COPY init.sql /docker-entrypoint-initdb.d/

# При необходимости можно добавить пользовательские параметры конфигурации
# COPY postgresql.conf /etc/postgresql/postgresql.conf
